### PR TITLE
Add Project Links

### LINKED ISSUE #5: Inconsistency when comparing dev- versions
Hey, I've integrated your package in my gitlab's CI, and have [dangerbot](https://danger.systems/js/usage/danger-process.html) post it as a comment to MR. Thanks for putting it together, it's a great tool, and other similar packages don't support custom gitlab domain.

I've encountered one minor inconsistency when using it for unfinished MRs. The "Operation" column for packages with `dev-*` is hard to predict. To pinpoint it, I've added to test `\IonBazan\ComposerDiff\Tests\Formatter\FormatterTest::testItRendersTheListOfOperations` this cases:

```
new UpdateOperation($this->getPackage('a/package-6', '0.5.2'), $this->getPackage('a/package-6', 'dev-feature', 'dev-feature 1234567')),
new UpdateOperation($this->getPackage('a/package-7', '0.5.2'), $this->getPackage('a/package-7', 'dev-main', 'dev-main 1234567')),
new UpdateOperation($this->getPackage('a/package-8', '0.5.2'), $this->getPackage('a/package-8', 'dev-master', 'dev-master 1234567')),
```

and the relevant test results were:

| Dev Packages | Operation  | Base               | Target              |
|--------------|------------|--------------------|---------------------|
| a/package-6  | Downgraded | 0.5.2              | dev-feature 1234567 |
| a/package-7  | Downgraded | 0.5.2              | dev-main 1234567    |
| a/package-8  | Upgraded   | 0.5.2              | dev-master 1234567  |

I think it would make sense to consider operations with `dev-` either always show up as `Upgraded`, or show something neutral, like `Changed`?

The current behavior is caused by `\Composer\Semver\VersionParser::normalizeDefaultBranch` called in `\Composer\Semver\Semver::sort` - it does:

```
if ($name === 'dev-master' || $name === 'dev-default' || $name === 'dev-trunk') {
     return '9999999-dev';
}
```

Also, I think the composer implementation of version comparison always assumes that changes involving `dev-` are an upgrade, no matter the change. Maybe in `\IonBazan\ComposerDiff\Formatter\AbstractFormatter::isUpgrade` you could simply use composer's `\Composer\Package\Version\VersionParser::isUpgrade`?

### LINKED ISSUE #15: Link to project?
If links are enabled, could there be a link to the project too?

### PR DESCRIPTION
**Pull request by giggsey**
Closes #15

### CODE REVIEW

**Comment by giggsey** [comment]
@IonBazan I haven't done the GitHub Formatter yet, as I'm unsure how it'll render urls.

For the markdown ones, I've put them as the package name rather than a new column

**Comment by IonBazan** [comment]
Looks nice! Just need to add some more coverage and it will be good to go.

For the GitHub formatter, I think it would not look good with the links as they are not clickable so let's leave it as is.

**Review by IonBazan — APPROVED** [review]
LGTM! 🚀

**Comment by IonBazan** [comment]
Thanks @giggsey! Your changes were released as https://github.com/IonBazan/composer-diff/releases/tag/v1.6.0

**Comment by giggsey** [comment]
Thanks for the prompt reviews

image

**Pull request merged**
